name: 'Simple bump version action'
description: 'Action to bump version'
author: 'kahovka'
inputs:
  githubtoken: 
    required: true
    description: 'github token for action'
    default: $ {{ secrets.GITHUB_TOKEN }} 
  packagepath: 
    required: true
    description: 'path to package.json'
    default: 'package.json'
  majortokens: 
    required: false
    description: 'keywords to bump major version'
  minortokens:
    required: false
    description: 'keywords to bump minor version'
  tagpolicy:
    required: false
    description: 'tag only some versions, takes minor, major, all. Minor includes major'
  squash:
    required: false
    description: 'whether to squash bump commit with previous'
    default: 0
runs:
  using: 'node12'
  main: 'dist/index.js'
